stages:
        - build
        - deploy

rpmbuild:
        stage: build
        image: gitlab-registry.cern.ch/cloud/ciadm
        except:
                - tags
        script:
                - printf '[cci7-iaas-newton] \nname=Cern rebuilds for IaaS Openstack \nbaseurl=http://linuxsoft.cern.ch/internal/repos/iaas7-newton-stable/x86_64/os/ \nenabled=1 \ngpgcheck=0 \npriority=5 \n' > /etc/yum.repos.d/cci7-iaas-newton.repo
                - if [ -z "$CI_BUILD_TAG" ]; then export CI_BUILD_TAG=$CI_DEFAULT_BUILD_TAG; fi
                - export parser=(${CI_BUILD_TAG//-/ })
                - sed -i s/CERN_VERSION_PLACEHOLDER/${parser[0]}/g hzrequestspanel.spec
                - sed -i s/CERN_RELEASE_PLACEHOLDER/${parser[1]}/g hzrequestspanel.spec
                - curl https://gitlab.cern.ch/cloud-infrastructure/cloud-dev/raw/master/gitlab/rpmbuild.sh | bash

kojicheck:
        stage: build
        image: gitlab-registry.cern.ch/cloud/ciadm
        script:
                - if [ -z "$CI_BUILD_TAG" ]; then export CI_BUILD_TAG=$CI_DEFAULT_BUILD_TAG; fi
                - export parser=(${CI_BUILD_TAG//-/ })
                - sed -i s/CERN_VERSION_PLACEHOLDER/${parser[0]}/g hzrequestspanel.spec
                - sed -i s/CERN_RELEASE_PLACEHOLDER/${parser[1]}/g hzrequestspanel.spec
                - curl https://gitlab.cern.ch/cloud-infrastructure/cloud-dev/raw/master/gitlab/kojicheck.sh | bash

kojibuild:
        stage: deploy
        image: gitlab-registry.cern.ch/cloud/ciadm
        only:
                - tags
        script:
                - export DIST='.el7'
                - if [ -z "$CI_BUILD_TAG" ]; then export CI_BUILD_TAG=$CI_DEFAULT_BUILD_TAG; fi
                - export parser=(${CI_BUILD_TAG//-/ })
                - sed -i s/CERN_VERSION_PLACEHOLDER/${parser[0]}/g hzrequestspanel.spec
                - sed -i s/CERN_RELEASE_PLACEHOLDER/${parser[1]}/g hzrequestspanel.spec
                - curl https://gitlab.cern.ch/cloud-infrastructure/cloud-dev/raw/master/gitlab/kojibuild.sh | bash
