stages:
        - build
        - deploy

rpmbuild:
        stage: build
        image: docker.cern.ch/cloud-infrastructure/kojiclient
        except:
                - master
        script:
                - curl https://gitlab.cern.ch/cloud-infrastructure/cloud-dev/raw/master/gitlab/rpmbuild.sh | bash
        tags:
                - cci-swarm-builder

kojicheck:
        stage: build
        image: docker.cern.ch/cloud-infrastructure/kojiclient
        except:
                - master
        script:
                - curl https://gitlab.cern.ch/cloud-infrastructure/cloud-dev/raw/master/gitlab/kojicheck.sh | bash
        tags:
                - cci-swarm-builder

kojibuild:
        stage: deploy
        image: docker.cern.ch/cloud-infrastructure/kojiclient
        only:
                - master
        script:
                - export DIST='.el7.cern'
                - sed -i 's/\.el7\.centos/\.el7\.cern/g' /etc/rpm/macros.dist
                - curl https://gitlab.cern.ch/cloud-infrastructure/cloud-dev/raw/master/gitlab/kojibuild.sh | bash
        tags:
                - cci-swarm-builder