stages:
  - test
  - deploy

before_script:
  - if [ -z "$CI_BUILD_TAG" ]; then export CI_BUILD_TAG=$CI_DEFAULT_BUILD_TAG; fi
  - export parser=(${CI_BUILD_TAG//-/ })
  - sed -i s/CERN_VERSION_PLACEHOLDER/${parser[0]}/g hzrequestspanel.spec
  - sed -i s/CERN_RELEASE_PLACEHOLDER/${parser[1]}/g hzrequestspanel.spec

rpmbuild:
  stage: test
  image: mkowalski/rpm-builder:latest
  except:
    - tags
  script:
    - curl https://gitlab.cern.ch/cloud-infrastructure/cloud-dev/raw/master/gitlab/rpmbuild.sh | bash

unittest:
  stage: test
  image: mkowalski/rpm-builder:latest
  except:
    - tags
  script:
    - sed -i s/%svc_pass%/$svc_pass/g test/hzrequestspanel_test.conf
    - mkdir -p /etc/openstack-dashboard && echo "$svcrdeck_keytab" > /etc/openstack-dashboard/svcrdeck.keytab.encoded
    - base64 --decode /etc/openstack-dashboard/svcrdeck.keytab.encoded > /etc/openstack-dashboard/svcrdeck.keytab
    - yum install -y cern-get-sso-cookie
    - git clone -b $cci_tools_branch https://gitlab.cern.ch/cloud-infrastructure/cci-tools.git && cd cci-tools && pip install -e . -r requirements.txt && cd ..
    - python -m pytest test

kojicheck:
  stage: deploy
  image: mkowalski/rpm-builder:latest
  only:
    - tags
  script:
    - curl https://gitlab.cern.ch/cloud-infrastructure/cloud-dev/raw/master/gitlab/kojicheck.sh | bash

kojibuild:
  stage: deploy
  image: mkowalski/rpm-builder:latest
  only:
    - tags
  script:
    - export DIST='.el7'
    - curl https://gitlab.cern.ch/cloud-infrastructure/cloud-dev/raw/master/gitlab/kojibuild.sh | bash
